---
name: Publish new slide deck
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Build & Deploy to GitHub Pages
        env: 
          # You may wish to customize MARP_ARGS
          # See https://github.com/marp-team/marp-cli#basic-usage for more details
          # For a multi-page site, try `MARP_ARGS: "-I slides/ --output dist/"`
          # Check examples for more: https://github.com/ralexander-phi/test-marp-action/blob/dev/README.md#example-sites
          # But to keep things simple, let's just convert a single README.md into index.html
          MARP_ARGS: "README.md -o index.html"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PUBLISH_TO_BRANCH: master
          BASE_URL: https://spetrosi.github.io/jak_psat_moderni_ucebnice/
        # consider using a tagged release here
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
        uses: ralexander-phi/marp-action@master
